// Maps a room's selected game to its pre-rendered Open Graph share card (generated by
// @branchout/brand into apps/web/public). The join page's generateMetadata calls this to unfurl a
// share link with the right game art and "Join my game" overlay. Kept a pure function so it is
// trivially unit-testable and has no server dependency.

/** A share card: the public image path plus ASCII alt text (Trellis language rules). */
export interface ShareCard {
  image: string;
  alt: string;
}

// Game ids match the control-plane's `selectedGame` values (see RoomClient's TRIVIA_GAME_ID).
const CARDS: Record<string, ShareCard> = {
  trivia: { image: '/share-trivia.png', alt: 'Join my Branch Out trivia game' },
  liarliar: { image: '/share-liarliar.png', alt: 'Join my Branch Out Liar Liar game' },
};

/** The generic invite card, for a room with no game picked yet or an unknown/expired code. */
const FALLBACK: ShareCard = { image: '/share-join.png', alt: 'Join my Branch Out game' };

/**
 * Pick the share card for a room's selected game. Unknown or null games (a room still in the
 * lobby, or a bad code) fall back to the generic invite card so every share link unfurls well.
 */
export function shareCardFor(game: string | null | undefined): ShareCard {
  return (game && CARDS[game]) || FALLBACK;
}
